select * from tab;
select * from DEFENSE_INFORMATION;

-- 계정저장소
create table ACCOUNT(
	USERID varchar2(30) PRIMARY KEY,
	USERPW varchar2(30) NOT NULL,
	USERLV NUMBER(3) DEFAULT 1, check(USERLV between 1 and 100),
	USEREXP NUMBER(10) DEFAULT 0,
	CREATIONDATE DATE DEFAULT SYSDATE,
	WIN NUMBER DEFAULT 0,
	LOSS NUMBER DEFAULT 0,
	KRW NUMBER DEFAULT 1000	
)

-- 유저경험치 테이블
create table USEREXP(
	USER_LV NUMBER(3) NOT NULL,check(USER_LV between 0 and 100),
	USER_NEEDEXP NUMBER(10) NOT NULL
)

-- 히터시퀀스
create SEQUENCE HITTER_STORAGE_SEQUNCE
	START WITH 1
	INCREMENT BY 1
	NOCYCLE;

-- 투수시퀀스
create SEQUENCE PITCHER_STORAGE_SEQUNCE
	START WITH 1
	INCREMENT BY 1
	NOCYCLE;

	
/* 투수저장소 */
CREATE TABLE PITCHER_STORAGE (
	PITCHERSEQ NUMBER PRIMARY KEY, /* 투수시퀀스 */
	USERID VARCHAR2(30) NOT NULL, /* 유저ID */
	PLAYERID NUMBER NOT NULL, /* 선수ID */
	PITCHERLV NUMBER(3) DEFAULT 1, check(PITCHERLV between 1 and 100), /* 투수LV */
	PITCHEREXP NUMBER(10) DEFAULT 0, /* 투수경험치 */
	POSITION VARCHAR2(3) check(POSITION in('st1','st2','st3','pb1','pb2','pb3','pb4'))
);

/* 타자저장소 */
CREATE TABLE HITTER_STORAGE (
	HITTERSEQ NUMBER PRIMARY KEY, /* 타자시퀀스 */
	USERID VARCHAR2(30) NOT NULL, /* 유저ID */
	PLAYERID NUMBER NOT NULL, /* 선수ID */
	HITTERLV NUMBER(3) DEFAULT 1, check(HITTERLV between 1 and 100), /* 타자LV */
	HITTEREXP NUMBER(10) DEFAULT 0, /* 타자경험치 */
	POSITION VARCHAR2(3) check(POSITION in('2','3','4','5','6','7','8','9','D','h1','h2','h3','h4')), /* 포지션 */
	BATTINGORDER NUMBER(1) check(BATTINGORDER in(1,2,3,4,5,6,7,8,9)) /* 타순 */
);

/* 투수정보 */
CREATE TABLE PITCHER_INFORMATION (
	PLAYERID NUMBER PRIMARY KEY, /* 선수ID */
	NAME VARCHAR2(30) NOT NULL, /* 이름 */
	CLUB varchar2(30) check(CLUB IN('KIA','두산','NC','롯데','넥센','LG','SK','한화','삼성','kt')),
	GRADE varchar2(1) check(GRADE IN('A','B','C')),
	ERA NUMBER(6,3) NOT NULL, /* 방어율 */
	G NUMBER(3) NOT NULL, /* 경기 */
	W NUMBER(3) NOT NULL, /* 승리 */
	L NUMBER(3) NOT NULL, /* 패배 */
	SV NUMBER(3) NOT NULL, /* 세이브 */
	HLD NUMBER(3) NOT NULL, /* 홀드 */
	IP NUMBER(3) NOT NULL, /* 이닝 */
	H NUMBER(4) NOT NULL, /* 피안타 */
	HR NUMBER(3) NOT NULL, /* 피홈런 */
	BB NUMBER(3) NOT NULL, /* 볼넷 */
	HBP NUMBER(3) NOT NULL, /* 사구 */
	SO NUMBER(4) NOT NULL /* 삼진 */
);

/* 타자정보 */
CREATE TABLE HITTER_INFORMATION (
	PLAYERID NUMBER NOT NULL, /* 선수ID */
	NAME VARCHAR2(30) NOT NULL, /* 이름 */
	CLUB varchar2(30) check(CLUB IN('KIA','두산','NC','롯데','넥센','LG','SK','한화','삼성','kt')),
	GRADE varchar2(1) check(GRADE IN('A','B','C')),
	AVG NUMBER(4,3) NOT NULL, /* 타율 */
	G NUMBER(3) NOT NULL, /* 경기 */
	PA NUMBER(4) NOT NULL, /* 타석 */
	R NUMBER(3) NOT NULL, /* 득점 */
	H NUMBER(3) NOT NULL, /* 안타 */
	B2 NUMBER(3) NOT NULL, /* 2루타 */
	B3 NUMBER(3) NOT NULL, /* 3루타 */
	HR NUMBER(3) NOT NULL, /* 홈런 */
	RBI NUMBER(3) NOT NULL, /* 타점 */
	SAC NUMBER(3) NOT NULL, /* 희생번트 */
	BB NUMBER(3) NOT NULL, /* 볼넷 */
	HBP NUMBER(3) NOT NULL, /* 사구 */
	SLG NUMBER(4,3) NOT NULL, /* 출루율 */
	OBP NUMBER(4,3) NOT NULL, /* 장타율 */
	OPS NUMBER(4,3) NOT NULL, /* OPS */
	RISP NUMBER(4,3) NOT NULL /* 득점권타율 */	
);



/* STORE_HITTER */
CREATE TABLE STORE_HITTER (
	HITTERID NUMBER NOT NULL, /* 타자ID */
	HITTERCHOICE0 NUMBER(3,3) /* 타자확률 */
);

/* STORE_PICHER */
CREATE TABLE STORE_PITCHER (
	PITCHERID NUMBER NOT NULL, /* 투수ID */
	PITCHERCHOICE0 NUMBER(3,3) /* 투수확률 */
);


/* PITCHEREXP */
CREATE TABLE PITCHEREXP (
	PITCHERLV NUMBER(3) NOT NULL, /* 투수LV */
	PITCHERNEEDEXP NUMBER(10) NOT NULL /* 투수경험치 */
);

/* HITTEREXP */
CREATE TABLE HITTEREXP (
	HITTERLV NUMERIC(3) NOT NULL, /* 타자LV */
	HITTEREXP NUMBER(10) NOT NULL /* 투수경험치 */
);

/* 수비정보 */
CREATE TABLE DEFENSE_INFORMATION (
	PLAYERID NUMBER NOT NULL, /* 선수ID */
	NAME VARCHAR2(30) NOT NULL, /* 이름 */
	CLUB VARCHAR2(30) NOT NULL, /* 구단 */
	GRADE varchar2(3) check(GRADE IN('A','B','C')),
	POSITION VARCHAR2(3) check(POSITION in('1','2','3','4','5','6','7','8','9','D')),
	G NUMBER(4) NOT NULL, /* 경기 */
	IP NUMBER(10,4) NOT NULL, /* 수비이닝 */
	E NUMBER(4) NOT NULL, /* 실책 */
	FPCT NUMBER(10,4) NOT NULL, /* 수비율 */
	CS NUMBER(10,4) NOT NULL /* 도루저지 */
);

ALTER TABLE PITCHER_STORAGE
	ADD
		CONSTRAINT FK_ACCOUNT_TO_PITCHER_STORAGE
		FOREIGN KEY (
			USERID
		)
		REFERENCES ACCOUNT (
			USERID
		);

ALTER TABLE PITCHER_STORAGE
	ADD
		CONSTRAINT FK_PITCHER_INFORMATION_TO_PITCHER_STORAGE
		FOREIGN KEY (
			PLAYERID
		)
		REFERENCES PITCHER_INFORMATION (
			PLAYERID
		);

ALTER TABLE HITTER_STORAGE
	ADD
		CONSTRAINT FK_ACCOUNT_TO_HITTER_STORAGE
		FOREIGN KEY (
			USERID
		)
		REFERENCES ACCOUNT (
			USERID
		);

ALTER TABLE HITTER_STORAGE
	ADD
		CONSTRAINT FK_HITTER_INFORMATION_TO_HITTER_STORAGE
		FOREIGN KEY (
			PLAYERID
		)
		REFERENCES HITTER_INFORMATION (
			PLAYERID
		);

ALTER TABLE DEFENSE_INFORMATION
	ADD
		CONSTRAINT FK_HITTER_INFORMATION_TO_DEFENSE_INFORMATION
		FOREIGN KEY (
			PLAYERID
		)
		REFERENCES HITTER_INFORMATION (
			PLAYERID
		);

ALTER TABLE DEFENSE_INFORMATION
	ADD
		CONSTRAINT FK_PITCHER_INFORMATION_TO_DEFENSE_INFORMATION
		FOREIGN KEY (
			PLAYERID
		)
		REFERENCES PITCHER_INFORMATION (
			PLAYERID
		);