-- account 생성
create table ACCOUNT(
	USERID varchar2(30) PRIMARY KEY,
	USERPW varchar2(30) NOT NULL,
	USERLV NUMBER(3) DEFAULT 1, check(USERLV between 1 and 100),
	USEREXP NUMBER(10) DEFAULT 0,
	CREATIONDATE DATE DEFAULT SYSDATE,
	WIN NUMBER DEFAULT 1,
	LOSS NUMBER DEFAULT 1,
	KRW NUMBER DEFAULT 1000	
)

-- 타자 시퀀스 생성
create SEQUENCE HITTER_STORAGE_SEQUNCE
	START WITH 1
	INCREMENT BY 1
	NOCYCLE;
	
-- 타자스토리지 생성
create table HITTER_STORAGE(
	HITTERSEQ NUMBER PRIMARY KEY,
	USERID varchar2(30) NOT NULL,
	HITTERID NUMBER(4) NOT NULL,
	HITTERLV NUMBER(3) DEFAULT 1, check(HITTERLV between 1 and 100),
	HITTEREXP NUMBER(10) DEFAULT 0,
	POSITION varchar2(3),
	BATTINGORDER NUMBER(1)
)

-- 타자정보 생성
create table HITTER_INFORMATION(
	HITTERID NUMBER(4) PRIMARY KEY,
	NAME varchar2(30) NOT NULL,
	AVG NUMBER(1,3) NOT NULL,
	PA NUMBER(4) NOT NULL,
	BB NUMBER(4) NOT NULL,
	SLG NUMBER(1,3) NOT NULL,
	RISP NUMBER(1,3) NOT NULL,
	CLUB varchar2(30), check(CLUB IN('KIA','두산','NC','롯데','넥센','LG','SK','한화','삼성','KT')),
	GRADE varchar2(1), check(GRADE IN('A','B','C'))	
)

-- 투수 시퀀스 생성
create SEQUENCE PITCHER_STORAGE_SEQUNCE
	START WITH 1
	INCREMENT BY 1
	NOCYCLE;

-- 투수스토리지 생성
create table PITCHER_STORAGE(
	PITCHERSEQ NUMBER PRIMARY KEY,
	USERID varchar2(30) NOT NULL,
	PITCHERID NUMBER(4) NOT NULL, 
	PITCHERLV NUMBER(3) DEFAULT 1, check(PITCHERLV between 1 and 100),
	PITCHEREXP NUMBER(10) DEFAULT 0,
	POSITION varchar2(3)
)

-- 타자정보 생성
create table PITCHER_INFORMATION(
	PITCHERID NUMBER(4) PRIMARY KEY,
	NAME varchar2(30) NOT NULL,
	ERA NUMBER(2,3) NOT NULL,
	IP NUMBER(4) NOT NULL,
	H NUMBER(4) NOT NULL,
	HR NUMBER(4) NOT NULL,
	BB NUMBER(4) NOT NULL,
	HBP NUMBER(4) NOT NULL,
	SO NUMBER(4) NOT NULL,
	AVG NUMBER(2,3) NOT NULL,
	CLUB varchar2(30) check(CLUB IN('KIA','두산','NC','롯데','넥센','LG','SK','한화','삼성','KT')),
	GRADE varchar2(1), check(GRADE IN('A','B','C'))	
)

-- 유저경험치 테이블
create table USEREXP(
	USER_LV NUMBER(3) NOT NULL,check(USER_LV between 0 and 100),
	USER_NEEDEXP NUMBER(10) NOT NULL
)

